- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /root/project/backend/app.tar.gz
    dest: /home/ubuntu/backend/


- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    ls -la
    printenv
    npm install
    npm run prestart:prod


- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm audit fix --audit-level=critical

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls
