- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory
- name: "move backend files to server."
  copy:
    src: /root/project/backend/app.tar.gz
    dest: /home/ubuntu/backend/
- name: "unzip."
  shell:
     cd /root/project/backend
     tar xvzf app.tar.gz 

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    ls -la
    printenv
    npm install
    npm run prestart:prod


- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm audit fix --audit-level=critical

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls
